# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fd66e99bdf266730d19259272ce0daff1db1d063501aacab791bf65408424db3877180729b6e518f80bbbf0a0cb297b3cddd2beed1f1dbb470dba9b65d1f2a4

test:
  secret_key_base: ac8591889f81aa21e28f4bfc5a117866b1a8e27292cca9f43dc9495f1ec08761cf6ac590767681e5d31088e2e0c4b16babd45771a14989d27abc6403a48f24d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
